# Generated by Django 3.2.20 on 2023-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rupifyuser',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='aadhar_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rupifyuser',
            name='user_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
