# Generated by Django 3.2.20 on 2023-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashAPI', '0002_auto_20230824_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rupifyuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
