# Generated by Django 3.2.20 on 2023-08-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashAPI', '0003_alter_rupifyuser_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rupifyuser',
            managers=[
            ],
        ),
    ]
