# Generated by Django 3.2.20 on 2023-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashAPI', '0005_remove_rupifyuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=200)),
                ('note_amount', models.IntegerField()),
            ],
        ),
    ]
